add support for multiple partitions/drives

diff --git a/trash/trash b/trash/trash
--- a/trash/trash
+++ b/trash/trash
@@ -16,47 +16,49 @@
   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 COMMENT
 
-version="trash v0.2.1"
+version="trash v0.3"
 
 function info {
-  if [[ $PWD != $trashcan/files ]]; then
-    echo "You must be in trashcan to display trashed file info."
-    echo "cd $trashcan/files"
-    return 1
-  fi
   for i; do
-    trashinfo=$trashcan/info/${i##*/}.trashinfo
-    [[ -f $trashinfo ]] || continue
-    cat "$trashinfo"
+    infofile=${i/\/files\//\/info\/}.trashinfo
+    [[ -f $infofile ]] || continue
+    cat "$infofile"
     echo "---------"
   done
   }
 
 function restore {
   for i; do
-    infofile="$trashcan"/info/`basename "$i"`.trashinfo
-    Path=`cat "$infofile" | grep -m1 Path= | cut -d'=' -f2`
-    if [[ -z $Path ]]; then
-      echo "Cannot restore $i due to missing filepath"
+    infofile=${i/\/files\//\/info\/}.trashinfo
+    opath=`grep -m1 Path= "$infofile" | cut -d'=' -f2`
+    if [[ -z $opath ]]; then
+      echo "cannot restore $i due to missing original filepath"
       continue
     fi
-    targetfolder=`dirname "$Path"`
-    j=0
-    while [[ -e $Path ]]; do
-      Path=${Path%_*}_$((j++))
-      if [[ $j -gt 99 ]]; then
-        echo "cannot restore $i due to too many conflicts in $targetfolder"
-        break
+    if [[ -h $i ]]; then
+      f=`readlink "$i"`
+      infofile2=${f/\/files\//\/info\/}.trashinfo
+      if [[ ! -e $f ]]; then
+        echo "$f no longer exists...restore fails."
+        continue
       fi
-    done
-    [[ -e $Path ]] && continue
-    mkdir -p "$targetfolder" && mv -n "$i" "$Path" && rm "$infofile"
+    else f=$i
+    fi
+    restoredir=`dirname "$opath"`
+    dupname "$i" "$restoredir"
+    [[ -e $restoredir/$fullfn ]] && continue
+    mkdir -p "$restoredir" || continue
+    mv "$f" "$restoredir/$fullfn" && rm -f "$infofile" "$i" "$infofile2"
   done
   }
 
-function move {
+function movetotrash {
   for i; do
-    if echo $i | grep -q "^$trashcan"; then
+    if [[ ! -e $i ]]; then
+      echo "$i doesn't exist"
+      continue
+    fi
+    if echo $i | grep -q /.Trash/; then
       echo "cannot trash $i because it's already in the trashcan"
       continue
     fi
@@ -64,21 +66,73 @@ function move {
       echo "full filepath is needed for $i"
       continue
     fi
-    if [[ $maxsize ]] && [[ `du -bs "$i" | awk '{print $1}'` -gt $maxsize ]]; then
+    if [[ `stat -c %s "$i"` -gt $maxsize ]]; then
       echo "skip $i because it's larger than $maxsize"
       continue
     fi
-    filename=`basename "$i"`
-    j=0
-    while [[ -e $trashcan/files/$filename ]]; do
-      filename=${filename%_*}_$((j++))
-      if [[ $j -gt 99 ]]; then
-        echo "cannot trash $i due to conflict in $trashcan"
-        break
-      fi
-    done
-    [[ -e $trashcan/files/$filename ]] && continue
-    mv "$i" "$trashcan/files/$filename" && echo -e "[$filename trash info]\nPath=$i\nDeletionDate=`date`" > "$trashcan/info/$filename.trashinfo"
+    topdir=`stat -c %m "$i"`
+    [[ $topdir == $trashcan_mntpoint ]] && localtrash=$trashcan || localtrash=$topdir/.Trash-$USER
+    if mkdir -p "$localtrash"/{files,info}; then
+      chmod +t "$localtrash"/{files,info}
+    else
+      echo "cannot create local trashcan at $trashcan"
+      continue
+    fi
+    dupname "$i" "$trashcan/files" || continue
+    [[ -e $trashcan/files/$fullfn ]] && continue
+    mv "$i" "$localtrash/files/$fullfn" || continue
+    echo -e "[$fullfn trash info]\nPath=$i\nDeletionDate=`date`" > "$localtrash/info/$fullfn.trashinfo"
+    [[ $localtrash == $trashcan ]] && continue
+    ln -sf "$localtrash/files/$fullfn" "$trashcan/files/$fullfn"
+    ln -sf "$localtrash/info/$fullfn.trashinfo" "$trashcan/info/$fullfn.trashinfo"
+  done
+  }
+
+function delete {
+  for i; do
+    infofile=${i/\/files\//\/info\/}.trashinfo
+    rm -f "$i" "$infofile"
+    if [[ -h $i ]]; then
+      i=`readlink "$i"`
+      infofile=${i/\/files\//\/info\/}.trashinfo
+      rm -f "$i" "$infofile"
+    fi
+  done
+  }
+
+function emptycans {
+  rm -rf "$trashcan"/{files,info}/*
+  IFS=$'\n'
+  mntpoints=(`mount`)
+  IFS=$oIFS
+  for i in "${mntpoints[@]}"; do
+    j=($i)
+    case ${j[2]} in
+      /home) localtrash=$HOME/.Trash ;;
+      /) localtrash=/.Trash-$USER ;;
+      *) localtrash=${j[2]}/.Trash-$USER ;;
+    esac
+    [[ -d $localtrash ]] && rm -rf "$localtrash"/{files,info}/*
+  done
+  }
+
+function dupname { #arg1: filepath arg2: targetdir ret: fullfn
+  j=0
+  fn=`basename "$1"`
+  ext=${fn##*.}
+  if [[ $ext == $fn ]]; then ext=""
+  else
+    ext=.$ext
+    fn=${fn%.*}
+  fi
+  fullfn=$fn$ext
+  while [[ -e $2/$fullfn ]]; do
+    fn=${fn%_*}_$((j++))
+    fullfn=$fn$ext
+    if [[ $j -gt 99 ]]; then
+      echo "too many conflict for $fpath in $targetdir"
+      return 1
+    fi
   done
   }
 
@@ -87,24 +141,30 @@ function usage {
   echo "$0 [--config cfg] files            #move file to trashcan"
   echo "$0 [--config cfg] --restore files  #restore item to its orginal location"
   echo "$0 [--config cfg] --empty          #remove all items in trashcan"
+  echo "$0 [--config cfg] --delete files   #remove selected items in trashcan"
   echo "$0 [--config cfg] --info files     #show trash file info"
+  echo "$0 [--config cfg] --list           #list trashcan content"
   echo
   echo "trashcan is $trashcan/files and max file size to trash is $maxsize"
   }
 
-if [[ $1 = --config ]]; then
+oIFS=$IFS
+if [[ $1 == --config ]]; then
   cfg=$2; shift 2
 fi
 [[ -f ${cfg:=$HOME/.trashrc} ]] && source "$cfg"
 maxsize=${maxsize:=1000000000}
 trashcan=${trashcan:=$HOME/.local/share/Trash}
-if ! mkdir -p "$trashcan/files" "$trashcan/info"; then
+trashcan_mntpoint=`stat -c %m "$trashcan"`
+if ! mkdir -p "$trashcan"/{files,info}; then
   echo "cannot create trashcan"; exit 1
 fi
 case $1 in
   --help|-h) usage ;;
   --info) shift; info "$@" ;;
-  --empty) rm -rf "$trashcan"/files/*; rm -rf "$trashcan"/info/* ;;
+  --empty) emptycans ;;
   --restore) shift; restore "$@" ;;
-  *) move "$@" ;;
+  --delete) shift; delete "$@" ;;
+  --list) ls --color=auto -l "$trashcan/files" ;;
+  *) movetotrash "$@" ;;
 esac
