- fixes create trash directories if they don't exist   - add message that user must be in trash directory in order to query trashed file info.

diff --git a/trunk/trash/trash b/trunk/trash/trash
--- a/trunk/trash/trash
+++ b/trunk/trash/trash
@@ -16,9 +16,14 @@
   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 COMMENT
 
-version="trash v0.2"
+version="trash v0.2.1"
 
 function info {
+  if [[ $PWD != $trashcan/files ]]; then
+    echo "You must be in trashcan to display trashed file info."
+    echo "cd $trashcan/files"
+    return 1
+  fi
   for i; do
     trashinfo=$trashcan/info/${i##*/}.trashinfo
     [[ -f $trashinfo ]] || continue
@@ -88,18 +93,17 @@ function usage {
   }
 
 if [[ $1 = --config ]]; then
-  if [[ -f $2 ]]; then cfg=$2; shift 2; else shift; fi
+  cfg=$2; shift 2
 fi
 [[ -f ${cfg:=$HOME/.trashrc} ]] && source "$cfg"
 maxsize=${maxsize:=1000000000}
 trashcan=${trashcan:=$HOME/.local/share/Trash}
-if ! mkdir -p "$trashcan"; then
-  echo "cannot create trashcan"
-  exit 1
+if ! mkdir -p "$trashcan/files" "$trashcan/info"; then
+  echo "cannot create trashcan"; exit 1
 fi
 case $1 in
   --help|-h) usage ;;
-  --info) shift; cd "$trashcan/files"; info "$@" ;;
+  --info) shift; info "$@" ;;
   --empty) rm -rf "$trashcan"/files/*; rm -rf "$trashcan"/info/* ;;
   --restore) shift; restore "$@" ;;
   *) move "$@" ;;
